'use client';

import { use, useState, useEffect } from 'react';
import dynamic from 'next/dynamic';
import Link from 'next/link';
import {
  ArrowLeft, ChevronRight, AlertTriangle, CheckCircle,
  AlertCircle, Monitor, Cpu, BookOpen, School,
  TrendingUp, Activity, Sparkles, RefreshCw,
} from 'lucide-react';
import ReactMarkdown from 'react-markdown';
import { getDistrictById, districtEducationData } from '@/lib/districtEducation';
import {
  computeEducationPriority, DEFAULT_BENCHMARKS,
  PILLAR_WEIGHTS, type GapDriver,
} from '@/lib/educationScore';
import StatCard from '@/components/StatCard';
import IndicatorBar from '@/components/IndicatorBar';
import HeroBanner from '@/components/HeroBanner';

const PillarRadar = dynamic(() => import('@/components/PillarRadar'), { ssr: false });

const LEVEL_COLOR: Record<string, string> = {
  Critical: '#ef4444', High: '#f59e0b', Moderate: '#3b82f6', Low: '#22c55e',
};
const SEVERITY_COLOR: Record<string, string> = {
  critical: 'text-red-400', high: 'text-amber-400', moderate: 'text-blue-400',
};

// ── Mistral Recommendations Component ────────────────────────
function MistralRecommendations({ districtId, districtName }: { districtId: string; districtName: string }) {
  const [recs, setRecs]       = useState<string[]>([]);
  const [loading, setLoading] = useState(false);
  const [source, setSource]   = useState<'mistral' | 'local' | null>(null);
  const [error, setError]     = useState(false);
  const [fetched, setFetched] = useState(false);

  const fetchRecs = async () => {
    setLoading(true); setError(false);
    try {
      const r = await fetch('/api/recommend', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ districtId }),
      });
      const data = await r.json();
      if (data.recommendations?.length) {
        setRecs(data.recommendations);
        setSource(data.source);
        setFetched(true);
      } else {
        setError(true);
      }
    } catch {
      setError(true);
    } finally {
      setLoading(false);
    }
  };

  // Auto-fetch on mount
  useEffect(() => { fetchRecs(); }, [districtId]);

  return (
    <div className="bg-gray-900 border border-gray-800 rounded-xl overflow-hidden">
      {/* Header */}
      <div className="px-5 py-4 border-b border-gray-800 flex items-center justify-between">
        <div className="flex items-center gap-2">
          <Sparkles size={15} className="text-amber-400" />
          <div>
            <p className="text-white font-semibold text-sm">Policy Recommendations</p>
            <p className="text-gray-600 text-xs font-mono">
              {source === 'mistral'
                ? 'Generated by Mistral AI · NISR-grounded'
                : source === 'local'
                ? 'ROVI scoring engine · NISR-based'
                : 'Evidence-based interventions · NST2 aligned'}
            </p>
          </div>
        </div>
        <button
          onClick={fetchRecs}
          disabled={loading}
          className="inline-flex items-center gap-1.5 text-xs text-gray-600 hover:text-gray-400 border border-gray-800 rounded-lg px-2.5 py-1.5 transition-colors disabled:opacity-40"
        >
          <RefreshCw size={11} className={loading ? 'animate-spin' : ''} />
          {loading ? 'Generating…' : 'Regenerate'}
        </button>
      </div>

      {/* Content */}
      <div className="p-5">
        {loading && !fetched ? (
          <div className="flex items-center gap-3 py-4">
            <div className="w-5 h-5 border-2 border-gray-700 border-t-amber-400 rounded-full animate-spin flex-shrink-0" />
            <p className="text-gray-500 text-sm font-mono">
              Analysing {districtName} education gaps…
            </p>
          </div>
        ) : error ? (
          <div className="flex items-center gap-2 py-2">
            <AlertCircle size={14} className="text-red-400" />
            <p className="text-red-400 text-xs">Could not generate recommendations.</p>
            <button onClick={fetchRecs} className="text-xs text-gray-500 hover:text-gray-300 underline ml-1">
              Retry
            </button>
          </div>
        ) : recs.length > 0 ? (
          <ol className="space-y-3">
            {recs.map((rec, i) => (
              <li key={i} className="flex items-start gap-3">
                <span className="flex-shrink-0 w-6 h-6 rounded-full bg-blue-600/20 border border-blue-600/30 text-blue-400 text-xs font-bold flex items-center justify-center mt-0.5">
                  {i + 1}
                </span>
                <p className="text-gray-300 text-sm leading-relaxed">{rec}</p>
              </li>
            ))}
          </ol>
        ) : null}

        {/* Source badge */}
        {fetched && (
          <div className="mt-4 pt-3 border-t border-gray-800 flex items-center gap-2">
            {source === 'mistral' ? (
              <span className="inline-flex items-center gap-1.5 text-xs text-amber-500 font-mono">
                <Sparkles size={11} /> Mistral AI · grounded on NISR district data
              </span>
            ) : (
              <span className="text-xs text-gray-700 font-mono">
                ROVI scoring engine · NISR ICT_use.px · smart.px · Primary.px
              </span>
            )}
          </div>
        )}
      </div>
    </div>
  );
}

// ── Main Page ─────────────────────────────────────────────────
export default function DistrictPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = use(params);
  const district = getDistrictById(id);

  if (!district) return (
    <div className="max-w-4xl mx-auto px-4 py-20 text-center">
      <p className="text-gray-500">District not found.</p>
      <Link href="/" className="text-blue-400 hover:underline mt-4 inline-block text-sm">
        Return to dashboard
      </Link>
    </div>
  );

  const result = computeEducationPriority(district, DEFAULT_BENCHMARKS);
  const color  = LEVEL_COLOR[result.priorityLevel];

  const circumference = 2 * Math.PI * 52;
  const offset = circumference - (result.priorityScore / 100) * circumference;

  const nearby = districtEducationData
    .filter(d => d.province === district.province && d.id !== district.id)
    .slice(0, 4)
    .map(d => ({ ...d, result: computeEducationPriority(d, DEFAULT_BENCHMARKS) }));

  return (
    <div className="max-w-7xl mx-auto px-4 py-8 space-y-6">

      {/* Breadcrumb */}
      <div className="flex items-center gap-1.5 text-xs text-gray-600">
        <Link href="/" className="hover:text-gray-400 transition-colors flex items-center gap-1">
          <ArrowLeft size={12} /> Dashboard
        </Link>
        <ChevronRight size={12} />
        <span>{district.province}</span>
        <ChevronRight size={12} />
        <span className="text-gray-400 font-medium">{district.name}</span>
      </div>

      {/* Hero */}
      <HeroBanner
        badge={`${district.province} · Education Gap Analysis`}
        title={
          <>
            {district.name}{' '}
            <span style={{ color }}>Education Gap</span>
          </>
        }
        subtitle={`Priority score: ${result.priorityScore}/100 · ${result.priorityLevel} priority · ${district.schoolAgePopulation}K school-age children · ${district.totalSchoolsEstimate} schools estimated`}
      >
        <span
          className="inline-flex items-center gap-1.5 text-xs font-semibold rounded border px-2.5 py-1"
          style={{ color, borderColor: color + '40', backgroundColor: color + '15' }}
        >
          {result.priorityLevel === 'Critical' ? <AlertTriangle size={12} /> :
           result.priorityLevel === 'Low'      ? <CheckCircle size={12} />   :
           <AlertCircle size={12} />}
          {result.priorityLevel} Priority
        </span>
      </HeroBanner>

      {/* ── Score ring + gap drivers + radar ─────────────── */}
      <div className="grid md:grid-cols-3 gap-5">

        {/* Score ring */}
        <div className="bg-gray-900 border border-gray-800 rounded-xl p-6 flex flex-col items-center gap-5">
          <div className="relative w-32 h-32">
            <svg className="w-full h-full -rotate-90" viewBox="0 0 120 120">
              <circle cx="60" cy="60" r="52" fill="none" stroke="#1f2937" strokeWidth="8" />
              <circle
                cx="60" cy="60" r="52" fill="none" strokeWidth="8"
                strokeDasharray={circumference} strokeDashoffset={offset}
                strokeLinecap="round"
                style={{ stroke: color, transition: 'stroke-dashoffset 1s' }}
              />
            </svg>
            <div className="absolute inset-0 flex flex-col items-center justify-center">
              <span className="text-3xl font-extrabold tabular-nums" style={{ color }}>
                {result.priorityScore}
              </span>
              <span className="text-gray-600 text-xs">/ 100</span>
            </div>
          </div>

          <div className="w-full text-center space-y-1">
            <p className="text-gray-500 text-xs font-mono">Education Gap Score</p>
            <p className="text-gray-700 text-xs font-mono">higher = larger gap = more intervention needed</p>
          </div>

          {/* Pillar mini-grid */}
          <div className="w-full grid grid-cols-2 gap-2">
            {[
              { label: 'ICT Readiness',  value: result.pillarScores.ict,            color: '#3b82f6', w: `${Math.round(PILLAR_WEIGHTS.ict * 100)}%`           },
              { label: 'Infrastructure', value: result.pillarScores.infrastructure, color: '#8b5cf6', w: `${Math.round(PILLAR_WEIGHTS.infrastructure * 100)}%` },
              { label: 'Resources',      value: result.pillarScores.resources,      color: '#f59e0b', w: `${Math.round(PILLAR_WEIGHTS.resources * 100)}%`      },
              { label: 'Digital',        value: result.pillarScores.digital,        color: '#10b981', w: `${Math.round(PILLAR_WEIGHTS.digital * 100)}%`        },
            ].map(({ label, value, color, w }) => (
              <div key={label} className="bg-gray-800/60 rounded-lg p-2.5 text-center">
                <p className="text-base font-bold tabular-nums" style={{ color }}>{value}</p>
                <p className="text-gray-600 text-xs leading-tight">{label}</p>
                <p className="text-gray-700 text-xs font-mono">{w} weight</p>
              </div>
            ))}
          </div>
        </div>

        {/* Gap Drivers */}
        <div className="bg-gray-900 border border-gray-800 rounded-xl p-5 space-y-4">
          <div className="flex items-center gap-1.5">
            <AlertCircle size={14} className="text-red-400" />
            <p className="text-white font-semibold text-sm">Gap Drivers</p>
          </div>
          <div className="space-y-4">
            {result.topDrivers.map((d: GapDriver) => (
              <div key={d.indicator} className="space-y-1">
                <div className="flex items-center justify-between text-xs">
                  <span className={`font-semibold ${SEVERITY_COLOR[d.severity] ?? 'text-gray-400'}`}>
                    {d.indicator}
                  </span>
                  <span className="text-gray-600 font-mono">
                    {d.districtValue}{d.unit.includes('%') ? '%' : ''} vs {d.nationalValue}{d.unit.includes('%') ? '%' : ''} nat.
                  </span>
                </div>
                <div className="w-full bg-gray-800 rounded-sm h-1.5">
                  <div
                    className="h-1.5 rounded-sm transition-all"
                    style={{
                      width: `${d.contribution}%`,
                      backgroundColor:
                        d.severity === 'critical' ? '#ef4444' :
                        d.severity === 'high'     ? '#f59e0b' : '#3b82f6',
                    }}
                  />
                </div>
                <p className="text-gray-700 text-xs font-mono">{d.pillar} · {d.contribution}pts</p>
              </div>
            ))}
          </div>

          {/* NST2 alignment */}
          {result.nst2Alignment.length > 0 && (
            <div className="border border-blue-900/40 bg-blue-950/20 rounded-lg p-3 space-y-1 mt-2">
              {result.nst2Alignment.map((n, i) => (
                <p key={i} className="text-blue-400 text-xs font-mono">{n}</p>
              ))}
            </div>
          )}
        </div>

        {/* Radar */}
        <div className="bg-gray-900 border border-gray-800 rounded-xl p-5">
          <p className="text-white font-semibold text-sm mb-0.5">Gap Profile by Pillar</p>
          <p className="text-gray-600 text-xs font-mono mb-3">gap score 0–100 · higher = worse</p>
          <PillarRadar
            economic={result.pillarScores.ict}
            social={result.pillarScores.infrastructure}
            agriculture={result.pillarScores.resources}
            infrastructure={result.pillarScores.digital}
          />
          <div className="mt-3 grid grid-cols-2 gap-1 text-xs text-gray-700 font-mono">
            <span>Economic → ICT</span>
            <span>Social → Infrastructure</span>
            <span>Agriculture → Resources</span>
            <span>Infra → Digital</span>
          </div>
        </div>
      </div>

      {/* ── Mistral AI Recommendations ────────────────────── */}
      <MistralRecommendations districtId={district.id} districtName={district.name} />

      {/* ── Indicator detail panels ───────────────────────── */}
      <div className="grid md:grid-cols-2 lg:grid-cols-4 gap-4">

        <div className="bg-gray-900 border border-gray-800 rounded-xl p-4 space-y-4">
          <div className="flex items-center gap-1.5 border-b border-gray-800 pb-3">
            <Monitor size={13} className="text-blue-400" />
            <p className="text-white font-semibold text-sm">ICT Readiness</p>
            <span className="ml-auto text-gray-700 text-xs font-mono">35%</span>
          </div>
          <IndicatorBar label="ICT Adoption" value={district.ictAdoptionPct}
            description={`${district.ictSchoolsCount} schools · national: ${DEFAULT_BENCHMARKS.ictPct}%`}
            inverted />
          <div className="bg-gray-800/40 rounded-lg p-2.5">
            <p className="text-gray-500 text-xs">Gap from national avg</p>
            <p className={`text-sm font-bold tabular-nums mt-0.5 ${district.ictAdoptionPct < DEFAULT_BENCHMARKS.ictPct ? 'text-red-400' : 'text-emerald-400'}`}>
              {district.ictAdoptionPct < DEFAULT_BENCHMARKS.ictPct
                ? `−${(DEFAULT_BENCHMARKS.ictPct - district.ictAdoptionPct).toFixed(1)} pp below`
                : `+${(district.ictAdoptionPct - DEFAULT_BENCHMARKS.ictPct).toFixed(1)} pp above`}
            </p>
            <p className="text-gray-700 text-xs font-mono mt-1">Source: NISR ICT_use.px</p>
          </div>
        </div>

        <div className="bg-gray-900 border border-gray-800 rounded-xl p-4 space-y-4">
          <div className="flex items-center gap-1.5 border-b border-gray-800 pb-3">
            <School size={13} className="text-purple-400" />
            <p className="text-white font-semibold text-sm">Infrastructure</p>
            <span className="ml-auto text-gray-700 text-xs font-mono">30%</span>
          </div>
          <IndicatorBar label="Schools / 1K Children" value={district.schoolsPer1000Children}
            max={6} unit="" description="NISR RPHC4 2022 estimate" inverted />
          <IndicatorBar label="Level Coverage" value={district.educationLevelCoverage}
            description="% of expected education levels" inverted />
          <div className="bg-gray-800/40 rounded-lg p-2.5 space-y-1">
            <p className="text-gray-500 text-xs">Est. schools: <span className="text-white font-bold">{district.totalSchoolsEstimate}</span></p>
            <p className="text-gray-500 text-xs">School-age pop: <span className="text-white font-bold">{district.schoolAgePopulation}K</span></p>
          </div>
        </div>

        <div className="bg-gray-900 border border-gray-800 rounded-xl p-4 space-y-4">
          <div className="flex items-center gap-1.5 border-b border-gray-800 pb-3">
            <BookOpen size={13} className="text-amber-400" />
            <p className="text-white font-semibold text-sm">Learning Resources</p>
            <span className="ml-auto text-gray-700 text-xs font-mono">20%</span>
          </div>
          <IndicatorBar label="Primary Book Ratio" value={district.primaryBookRatio}
            max={5} unit=":1" description={`National: ${DEFAULT_BENCHMARKS.primaryBookRatio}:1 · NISR Primary.px`} />
          <IndicatorBar label="Secondary Book Ratio" value={district.secondaryBookRatio}
            max={5} unit=":1" description="NISR lower_secondary.px" />
          <div className="bg-gray-800/40 rounded-lg p-2.5">
            <p className="text-gray-500 text-xs">NST2 target: 1:1 ratio</p>
            <p className="text-xs mt-1">
              <span className={district.primaryBookRatio <= 1.5 ? 'text-emerald-400' : 'text-amber-400'}>
                Primary: {district.primaryBookRatio}:1
              </span>
              {' · '}
              <span className={district.secondaryBookRatio <= 1.2 ? 'text-emerald-400' : 'text-amber-400'}>
                Secondary: {district.secondaryBookRatio}:1
              </span>
            </p>
          </div>
        </div>

        <div className="bg-gray-900 border border-gray-800 rounded-xl p-4 space-y-4">
          <div className="flex items-center gap-1.5 border-b border-gray-800 pb-3">
            <Cpu size={13} className="text-emerald-400" />
            <p className="text-white font-semibold text-sm">Digital Equity</p>
            <span className="ml-auto text-gray-700 text-xs font-mono">15%</span>
          </div>
          <IndicatorBar label="Smart Classrooms" value={district.smartClassroomPct}
            description={`${district.smartSchoolsCount} schools · national: ${DEFAULT_BENCHMARKS.smartPct}%`}
            inverted />
          <div className="bg-gray-800/40 rounded-lg p-2.5">
            <p className="text-gray-500 text-xs">Gap from national avg</p>
            <p className={`text-sm font-bold tabular-nums mt-0.5 ${district.smartClassroomPct < DEFAULT_BENCHMARKS.smartPct ? 'text-red-400' : 'text-emerald-400'}`}>
              {district.smartClassroomPct < DEFAULT_BENCHMARKS.smartPct
                ? `−${(DEFAULT_BENCHMARKS.smartPct - district.smartClassroomPct).toFixed(1)} pp below`
                : `+${(district.smartClassroomPct - DEFAULT_BENCHMARKS.smartPct).toFixed(1)} pp above`}
            </p>
            <p className="text-gray-700 text-xs font-mono mt-1">Source: NISR smart.px</p>
          </div>
        </div>
      </div>

      {/* ── Context stats ─────────────────────────────────── */}
      <div className="grid grid-cols-2 md:grid-cols-4 gap-3">
        <StatCard label="Poverty Rate"     value={`${district.povertyRate}%`}  sub="NISR EICV5 2023/24" accent="red"    />
        <StatCard label="Rural Population" value={`${district.ruralPct}%`}     sub="NISR RPHC4 2022"   accent="amber"  />
        <StatCard label="Youth NEET Rate"  value={`${district.youthNEET}%`}    sub="NISR LFS 2024"     accent="purple" />
        <StatCard label="Level Coverage"   value={`${district.educationLevelCoverage}%`} sub="Education levels present" accent="blue" />
      </div>

      {/* ── Province comparison ───────────────────────────── */}
      {nearby.length > 0 && (
        <div className="bg-gray-900 border border-gray-800 rounded-xl overflow-hidden">
          <div className="px-5 py-3 border-b border-gray-800">
            <p className="text-white font-semibold text-sm">Compare within {district.province}</p>
            <p className="text-gray-600 text-xs font-mono">education gap scores</p>
          </div>
          <div className="grid md:grid-cols-2 lg:grid-cols-4 divide-y md:divide-y-0 md:divide-x divide-gray-800">
            {nearby.map(n => (
              <Link key={n.id} href={`/district/${n.id}`}
                className="p-5 hover:bg-gray-800/40 transition-colors">
                <p className="text-white font-semibold text-sm">{n.name}</p>
                <p className="text-2xl font-bold tabular-nums mt-2"
                  style={{ color: LEVEL_COLOR[n.result.priorityLevel] }}>
                  {n.result.priorityScore}
                </p>
                <span className="text-xs font-semibold"
                  style={{ color: LEVEL_COLOR[n.result.priorityLevel] }}>
                  {n.result.priorityLevel}
                </span>
              </Link>
            ))}
          </div>
        </div>
      )}

      {/* ── Methodology note ──────────────────────────────── */}
      <div className="bg-gray-900/50 border border-gray-800 rounded-xl p-4">
        <p className="text-gray-600 text-xs font-mono leading-relaxed">
          {result.confidenceNote}
        </p>
      </div>

      {/* ── Action buttons ────────────────────────────────── */}
      <div className="flex flex-wrap gap-3">
        <Link href={`/simulator?district=${district.id}`}
          className="inline-flex items-center gap-2 bg-blue-600 hover:bg-blue-700 text-white font-semibold text-sm px-5 py-2.5 rounded-lg transition-colors">
          <Activity size={15} /> Run Intervention Simulation
        </Link>
        <Link href="/assistant"
          className="inline-flex items-center gap-2 bg-gray-800 hover:bg-gray-700 border border-gray-700 text-gray-300 font-medium text-sm px-5 py-2.5 rounded-lg transition-colors">
          Query Education Data
        </Link>
        <Link href="/"
          className="inline-flex items-center gap-1.5 text-gray-500 hover:text-gray-300 text-sm px-4 py-2.5 rounded-lg border border-gray-800 hover:border-gray-700 transition-colors">
          <ArrowLeft size={14} /> All Districts
        </Link>
      </div>
    </div>
  );
}
